name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: clone ${{ github.repository }}
        uses: actions/checkout@v4
      - name: setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: run tests
        run: bundle exec rspec
